import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'index': 'src/index.ts',
    'adapters/express': 'src/adapters/express.ts',
    'adapters/fetch': 'src/adapters/fetch.ts',
    'stores/redis': 'src/stores/redis.ts',
    'adapters/hono': 'src/adapters/hono.ts',
    'adapters/fastify': 'src/adapters/fastify.ts',
    'adapters/koa': 'src/adapters/koa.ts',
    'adapters/next': 'src/adapters/next.ts',
    'adapters/otel': 'src/adapters/otel.ts',
    'stores/postgres': 'src/stores/postgres.ts',
    'stores/redis-adapters': 'src/stores/redis-adapters.ts',
    'dashboard/server': 'src/dashboard/server.ts',
    'dashboard/bin': 'src/dashboard/bin.ts',
    'stores/cloudflare': 'src/stores/cloudflare.ts',
    'token-budget/index': 'src/token-budget/index.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  target: 'node18',
  outDir: 'dist',
  treeshake: true,
  external: ['ioredis', 'express', '@opentelemetry/api', 'pg'],
});
